# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 7
    binary: oci-registry-p2p

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"


dockers:
- image_templates:
    - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use_buildx: true
  goos: linux
  goarch: amd64
  build_flag_templates:
   - "--pull"
   - "--build-arg=ARCH=linux/amd64"
   - "--label=org.opencontainers.image.created={{ .Date }}"
   - "--label=org.opencontainers.image.name={{ .ProjectName }}"
   - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
   - "--label=org.opencontainers.image.version={{ .Version }}"
   - "--label=org.opencontainers.image.source={{ .GitURL }}"
   - "--platform=linux/amd64"

- image_templates:
  - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use_buildx: true
  goos: linux
  goarch: amd64
  build_flag_templates:
   - "--pull"
   - "--build-arg=ARCH=linux/amd64"
   - "--label=org.opencontainers.image.created={{ .Date }}"
   - "--label=org.opencontainers.image.name={{ .ProjectName }}"
   - "--label=org.'opencontainers.image.revision={{ .FullCommit }}"
   - "--label=org.opencontainers.image.version={{ .Version }}"
   - "--label=org.opencontainers.image.source={{ .GitURL }}"
   - "--platform=linux/amd64"

- image_templates:
  - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-armv7'
  dockerfile: Dockerfile
  goos: linux
  goarch: arm
  goarm: 7
  build_flag_templates:
   - "--pull"
   - "--build-arg=ARCH=linux/arm/v7"
   - "--label=org.opencontainers.image.created={{ .Date }}"
   - "--label=org.opencontainers.image.name={{ .ProjectName }}"
   - "--label=org.'opencontainers.image.revision={{ .FullCommit }}"
   - "--label=org.opencontainers.image.version={{ .Version }}"
   - "--label=org.opencontainers.image.source={{ .GitURL }}"
   - "--platform=linux/arm/v7"

- image_templates:
  - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  goos: linux
  goarch: arm64
  build_flag_templates:
   - "--pull"
   - "--build-arg=ARCH=linux/arm64"
   - "--label=org.opencontainers.image.created={{ .Date }}"
   - "--label=org.opencontainers.image.name={{ .ProjectName }}"
   - "--label=org.'opencontainers.image.revision={{ .FullCommit }}"
   - "--label=org.opencontainers.image.version={{ .Version }}"
   - "--label=org.opencontainers.image.source={{ .GitURL }}"
   - "--platform=linux/arm64"

docker_manifests:
- name_template: 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}'
  image_templates:
    - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-amd64'
    - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-armv7'
    - 'docker.io/uvgroovy/oci-registry-p2p:{{ .Tag }}-arm64'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
