{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "docker-registry-p2p.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: registry-tls
  issuerRef:
    kind: Issuer # TODO
    name: letsencrypt-staging # TODO
  dnsNames:
  - '*.example.com' # TODO
  - example.com # TODO
  - example.org # TODO
{{- end }}