apiVersion: apps/v1
{{- if .Values.deployment.statefulSet }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "docker-registry-p2p.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry-p2p.labels" . | nindent 4 }}
spec:
{{- if .Values.deployment.statefulSet }}
  serviceName: {{ include "docker-registry-p2p.fullname" . }}
{{- end }}
{{- if .Values.deployment.replicaCount }}
  replicas: {{ .Values.deployment.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "docker-registry-p2p.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5001'
        prometheus.io/path: '/metrics'
      labels:
        {{- include "docker-registry-p2p.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "docker-registry-p2p.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - serve
        - /config/config.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REGISTRY_STORAGE_ORBITDB_ADDRESS
          value: {{ .Values.orbitdb.ipfsPath | quote }}
        - name: REGISTRY_STORAGE_ORBITDB_DBADDRESS
          value: {{ .Values.orbitdb.orbitdbAddress | quote }}
{{- if .Values.deployment.statefulSet }}
        - name: REGISTRY_STORAGE_ORBITDB_CACHEDIR
          value: /cache
{{- end }}
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          - name: debug
            containerPort: 5001
            protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        readinessProbe:
          httpGet:
{{- if .Values.tls.enabled }}
            scheme: HTTPS
{{- end }}
            path: /
            port: http
        volumeMounts:
          - mountPath: /config
            name: config
{{- if .Values.tls.enabled }}
          - mountPath: "/etc/certs"
            name: tls
            readOnly: true
{{- end}}
{{- if .Values.deployment.statefulSet }}
          - mountPath: /cache
            name: cache
{{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "docker-registry-p2p.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
{{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName | default (include "docker-registry-p2p.fullname" .) }}
{{- end }}
{{- if .Values.deployment.statefulSet }}
  volumeClaimTemplates:
  - metadata:
      name: cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
{{- end }}