{{- if .Values.tls.createSelfSigned }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "docker-registry-p2p.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry-p2p.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "docker-registry-p2p.gen-certs" . ) | indent 2 }}
{{- end }}