version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  ipfs:
    ipfsapiaddress: /ip4/127.0.0.1/tcp/5001
    writeipnskey: self
    readonlyipnskeys: "k51qzi5uqu5dlj2qkibv67ep4sdsa73s9asv2g3um5j441i80ks15e1afi7waz"

http:
  addr: localhost:5000
  net: tcp
  prefix: /
  host: https://localhost:5000
  secret: asecretforlocaldevelopment
  relativeurls: true
  draintimeout: 60s
  debug:
    addr: localhost:5010
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
  tls:
    certificate: cert.pem
    key: key.pem