version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging

storage:
  inmemory: {}

middleware:
  repository:
    - name: ipfs
      options:
#        ipfsapiaddress: /ip4/127.0.0.1/tcp/5001
        ipfsapiaddress: /ip4/192.168.1.3/tcp/31341
http:
  addr: localhost:5000
  net: tcp
  prefix: /
  host: https://localhost:5000
  secret: asecretforlocaldevelopment
  relativeurls: true
  draintimeout: 60s
  debug:
    addr: localhost:5010
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
  tls:
    certificate: cert.pem
    key: key.pem