apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oci-registry-p2p.fullname" . }}
  labels:
    {{- include "oci-registry-p2p.labels" . | nindent 4 }}
data:
  config.yaml: |
    version: 0.1
    log:
      accesslog:
        disabled: true
      level: debug
      formatter: text
      fields:
        service: registry
        environment: staging
    storage:
      ipfs:
        ipfsapiaddress: {{ .Values.ipfs.address | quote  }}
        writeipnskey: {{ .Values.ipfs.publishIpnsKey | quote  }}
        readonlyipnskeys: {{ .Values.ipfs.readonlyipnskeys | quote }}

    middleware:
      repository:
        - name: ipfs
          options:
            ipfsapiaddress: {{ .Values.ipfs.address | quote  }}
    http:
      addr: 0.0.0.0:5000
      net: tcp
      prefix: /
      host: {{ .Values.registry.http.host }}
      relativeurls: true
      draintimeout: 60s
      debug:
        addr: 0.0.0.0:5001
        prometheus:
          enabled: true
          path: /metrics

      headers:
        X-Content-Type-Options: [nosniff]
      http2:
        disabled: false
      tls:
        certificate: /etc/certs/tls.crt
        key: /etc/certs/tls.key