apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oci-registry-p2p.fullname" . }}
  labels:
    {{- include "oci-registry-p2p.labels" . | nindent 4 }}
spec:
{{- if .Values.deployment.replicaCount }}
  replicas: {{ .Values.deployment.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "oci-registry-p2p.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5001'
        prometheus.io/path: '/metrics'
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "oci-registry-p2p.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ include "oci-registry-p2p.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - serve
        - /config/config.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          - name: debug
            containerPort: 5001
            protocol: TCP
        readinessProbe:
          httpGet:
{{- if .Values.tls.enabled }}
            scheme: HTTPS
{{- end }}
            path: /
            port: http
        volumeMounts:
          - mountPath: /config
            name: config
{{- if .Values.tls.enabled }}
          - mountPath: "/etc/certs"
            name: tls
            readOnly: true
{{- end}}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "oci-registry-p2p.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
{{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName | default (include "oci-registry-p2p.fullname" .) }}
{{- end }}
