apiVersion: v1
kind: Service
metadata:
  name: {{ include "oci-registry-p2p.fullname" . }}
  labels:
    {{- include "oci-registry-p2p.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oci-registry-p2p.selectorLabels" . | nindent 4 }}
